CREATE TABLE IF NOT EXISTS "surveys" (
	"id" SERIAL PRIMARY KEY,
	"slug" uuid DEFAULT gen_random_uuid(),
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
