CREATE TABLE IF NOT EXISTS "questions" (
	"id" SERIAL PRIMARY KEY,
	"question" VARCHAR(255) NOT NULL,
	"explanation" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
