CREATE TABLE IF NOT EXISTS "ranks" (
	"id" SERIAL PRIMARY KEY,
  "survey_id" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("survey_id") REFERENCES "surveys" ("id")
);
